#version 450

#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_buffer_reference2 : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable

#include "includes/BufferInfo.glsl"
#include "includes/RenderModelData.glsl"
#include "includes/SceneModelData.glsl"

struct VkDrawIndexedIndirectCommand
{
	uint indexCount;
	uint instanceCount;
	uint firstIndex;
	int  vertexOffset;
	uint firstInstance;
};

layout(buffer_reference, std430) buffer OutputBuffer {
    uint count;
	VkDrawIndexedIndirectCommand draw_cmd[];
};

layout(push_constant) uniform constants
{
	BufferInfo model_input_model_data;
	BufferInfo model_input_models;
	BufferInfo model_output_buffer;
	uint draw_count;
} push_const;

layout(local_size_x = 128) in;

void main() {
	uint idx = gl_GlobalInvocationID.x;

	RenderModelDataBuffer render_info = RenderModelDataBuffer(push_const.model_input_model_data.address);
	SceneModelDataBuffer scene_info = SceneModelDataBuffer(push_const.model_input_models.address);
	OutputBuffer output_buf = OutputBuffer(push_const.model_output_buffer.address);
	
	if(idx >= push_const.draw_count) { return; }
	
	uint output_index = atomicAdd(output_buf.count, 1);

	output_buf.draw_cmd[output_index] = VkDrawIndexedIndirectCommand(
		render_info.data[scene_info.model_data[idx].id].ind_count, 
		1, 
		render_info.data[scene_info.model_data[idx].id].ind_offset, 
		render_info.data[scene_info.model_data[idx].id].vert_offset, 
		idx);
}