#version 450

#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_buffer_reference2 : enable
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : enable

struct BufferInfo {
  uint64_t address;
  uint64_t offset;
  uint64_t size;
};

struct VkDrawIndexedIndirectCommand
{
	uint indexCount;
	uint instanceCount;
	uint firstIndex;
	int  vertexOffset;
	uint firstInstance;
};

struct ModelInfo
{
	int vert_offset;
	uint ind_count;
	uint ind_offset;
	uint material_type;  
	int base_tex_id;
	int normal_tex_id;
	int emission_tex_id;
	int metalness_tex_id;
	int diffuse_roughness_id;
	int ambient_occlusion_id;
};

layout(buffer_reference, std430, buffer_reference_align = 16) buffer ModelData {
	ModelInfo model_infos[];
};

layout(buffer_reference, std430, buffer_reference_align = 16) buffer ModelIDs {
	uint model_ids[];
};

layout(buffer_reference, std430) buffer OutputBuffer {
    uint count;
	VkDrawIndexedIndirectCommand draw_cmd[];
};

layout(push_constant) uniform constants
{
	BufferInfo model_input_model_data;
	BufferInfo model_input_models;
	BufferInfo model_output_buffer;
	uint draw_count;
} push_const;

layout(local_size_x = 128) in;

void main() {
	uint idx = gl_GlobalInvocationID.x;

	if(idx >= push_const.draw_count) { return; }

	ModelData model_data = ModelData(push_const.model_input_model_data.address);
	ModelIDs model_ids = ModelIDs(push_const.model_input_models.address);
	OutputBuffer output_buf = OutputBuffer(push_const.model_output_buffer.address);
	
	uint output_index = atomicAdd(output_buf.count, 1);
	
	output_buf.draw_cmd[output_index] = VkDrawIndexedIndirectCommand(
		model_data.model_infos[model_ids.model_ids[idx]].ind_count, 
		1, 
		model_data.model_infos[model_ids.model_ids[idx]].ind_offset, 
		model_data.model_infos[model_ids.model_ids[idx]].vert_offset, 
		idx);
}